### ISSUE TITLE
Explode > Dedupe Can create a 0/1 length LineString

### ISSUE THREAD

**Issue by ingalls** [ingalls/pt2itp#108]
Relevant Error:

```
ok - Splitting Data [===                 ] 13% 5401.4s

/mnt/data/pt2itp/node_modules/@turf/helpers/index.js:123
    if (coordinates.length < 2) throw new Error('Coordinates must be an array of two or more positions');
                                ^
Error: Coordinates must be an array of two or more positions
    at Object.lineString (/mnt/data/pt2itp/node_modules/@turf/helpers/index.js:123:39)
    at main (/mnt/data/pt2itp/lib/explode.js:85:48)
    at pool.query (/mnt/data/pt2itp/lib/split.js:57:24)
    at /mnt/data/pt2itp/node_modules/pg-pool/index.js:60:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Currently Blocking FR

**Comment by ingalls** [comment]
Another fatal error when running FI

```
/mnt/data/pt2itp/node_modules/fast-levenshtein/levenshtein.js:31
        str2Len = str2.length;
                      ^
TypeError: Cannot read property 'length' of null
    at get (/mnt/data/pt2itp/node_modules/fast-levenshtein/levenshtein.js:31:23)
    at module.exports (/mnt/data/pt2itp/lib/linker.js:39:24)
    at pool.query (/mnt/data/pt2itp/lib/match.js:63:23)
    at /mnt/data/pt2itp/node_modules/pg-pool/index.js:60:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
